name: sync-glitch

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  git-sync:
    runs-on: ubuntu-latest
    steps:
    - name: git-sync
      uses: wei/git-sync@v3
      with:
        source_repo: "lazho/addle.git"
        source_branch: "main"
        destination_repo: ${{ secrets.glitch_git_URL }}
        destination_branch: "master"
